platform :'ios','9.0'
target 'PandaVideo' do
  pod 'YYModel'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'Bugly'
  pod 'CocoaAsyncSocket'
  pod 'FMDB'
  pod 'Toast'
  pod 'TYAttributedLabel'
  pod 'MJRefresh'
  pod 'JPush'
  use_frameworks!
end
